---
skydive_analyzer_docker_extra_env:
skydive_etcd_embedded: yes
skydive_etcd_port: 12379
skydive_etcd_scheme: http
skydive_etcd_servers:
skydive_analyzer_docker_image: skydive/skydive
skydive_analyzer_docker_command: analyzer
skydive_auto_fabric: yes
skydive_fabric_default_interface: eth0
skydive_fabric_tor_name: tor1
skydive_fabric_tor_mtu: 1500
skydive_basic_auth_file: /var/lib/skydive/skydive.secret
