language: go
go_import_path: github.com/redhat-cip/skydive

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - sudo apt-get update -qq
    - sudo apt-get install -qq protobuf-compiler
    - make genlocalfiles

script:
    - make install
    - ./coverage.sh --coveralls
