---
- name: Generate systemd unit file
  become: yes
  template:
    src: "{{ role_path }}/templates/skydive.service.j2"
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: Restart service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
