---
- selinux:
    policy: targeted
    state: permissive

- shell: "dnf copr enable -y ganto/lxd"

- package:
    name: lxd
    state: present

- lineinfile:
    path: /etc/subuid
    line: 'root:1000000:65536'

- lineinfile:
    path: /etc/subgid
    line: 'root:1000000:65536'

- service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - lxd

- shell: "lxd init --auto"
