---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- package:
    name: "{{ item }}"
    state: present
  with_items:
     - git
     - wget
     - unzip
     - gcc
     - make
     - openvswitch
     - docker
     - libpcap-devel
     - libxml2-devel
     - screen
     - inotify-tools
     - iperf
     - libselinux-python
     - bridge-utils
     - perl-Graph-Easy
     - rpm-build
     - rpmlint
     - libvirt
     - libvirt-client
     - vagrant-libvirt
     - ansible
     - numactl-devel
     - kernel-devel
     - python3-virtualenv
     - llvm-devel
     - clang-devel
     - elfutils-libelf-devel
     - kubernetes-client
     - jq
     - aria2
     - tcpdump
     - socat
     - python2-virtualenv
     - python3-virtualenv
     - virt-what

- service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - openvswitch
    - docker

- name: Configure docker
  become: yes
  tasks:
  - group:
      name: docker
      state: present
  - user:
      name: vagrant
      groups: vagrant, docker
      append: yes
  - service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - docker

- include: lxd.yml
  when: ansible_distribution == "Fedora"

- include: protobuf.yml

- include: static.yml

- include: gimme.yml
  tags:
    - vagrant
